Update ContactLock.php
Changed from and where clauses to be static, to resolve `
Fatal error: Cannot make static method CRM_Contact_BAO_Query_Interface::from() non static in class CRM_Civicase_BAO_Query_ContactLock in /Library/WebServer/Documents/drupal/aaa-internal/htdocs/sites/default/files/civicrm/ext/uk.co.compucorp.civicase/CRM/Civicase/BAO/Query/ContactLock.php on line 21` error.